// import Image from 'next/image'
import { Inter } from "next/font/google";
import Head from "next/head";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import Image from "next/image";
import Weather from "@/components/Weather";
import Loading from "@/components/Loading";

export default function Home() {
  const [city, setCity] = useState("");
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env._WEATHER_APP_KEY}`;
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((res) => {
      setWeather(res.data);
      // console.log(res.data);
    });
    setCity("");
    setLoading(false);
  };
  if (loading) {
    return <Loading />;
  } else {
    return (
      <div>
        <Head>
          <title>Weather _ next App</title>
          <meta name="description" content="Generated By Next App" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className=" absolute top-0 bottom-0 right-0 left-0 z-[1] bg-black/40" />
        <Image
          layout="fill"
          src="https://images.unsplash.com/photo-1592210454359-9043f067919b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8d2VhdGhlcnxlbnwwfHwwfHw%3D&w=1000&q=80"
          alt=""
          className=" object-cover"
        />

        <div className=" relative flex justify-center text-white m-auto p-20 max-w-[500] z-[10] ">
          <form
            onSubmit={fetchWeather}
            className=" gap-32 flex justify-between border-solid border border-gray-100 py-4 px-10 rounded-md"
          >
            <input
              type="text"
              placeholder="Search A Country"
              className=" bg-transparent focus:outline-none text-white placeholder:text-gray-200"
              onChange={(e) => {
                const val = e.target.value;
                // console.log(val);
                setCity(val);
              }}
            />
            <button onClick={fetchWeather}>
              {<BsSearch size={20}></BsSearch>}
            </button>
          </form>
        </div>
        {weather.main && <Weather data={weather} className=" z-20" />}
      </div>
    );
  }
}
